/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    events: Event;
    groups: Group;
    registrations: Registration;
    'form-assignments': FormAssignment;
    locations: Location;
    attendings: Attending;
    'team-members': TeamMember;
    academic_titles: AcademicTitle;
    'feature-requests': FeatureRequest;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    groups: {
      members_table: 'users';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    registrations: RegistrationsSelect<false> | RegistrationsSelect<true>;
    'form-assignments': FormAssignmentsSelect<false> | FormAssignmentsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    attendings: AttendingsSelect<false> | AttendingsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    academic_titles: AcademicTitlesSelect<false> | AcademicTitlesSelect<true>;
    'feature-requests': FeatureRequestsSelect<false> | FeatureRequestsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-content': HomeContent;
    'terms-content': TermsContent;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-content': HomeContentSelect<false> | HomeContentSelect<true>;
    'terms-content': TermsContentSelect<false> | TermsContentSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Changing roles auto-syncs the user's groups. Admin role is equivalent to President.
   */
  roles: ('visitor' | 'member' | 'staff_probation' | 'staff' | 'deputy_vp' | 'vp' | 'admin' | 'superadmin')[];
  groups?: (number | Group)[] | null;
  /**
   * Auto-syncs to the corresponding department group
   */
  department?: ('IA' | 'EA' | 'OD' | 'AD' | 'CC' | 'PR') | null;
  google_id?: string | null;
  image_url?: string | null;
  dob?: string | null;
  age?: number | null;
  name_thai?: {
    first_name?: string | null;
    last_name?: string | null;
    nickname?: string | null;
  };
  full_name_thai?: string | null;
  profile_complete?: boolean | null;
  name_english?: {
    first_name?: string | null;
    last_name?: string | null;
    nickname?: string | null;
  };
  academic?: {
    student_id?: string | null;
    /**
     * Auto-syncs to the corresponding academic track group
     */
    track?: ('MD' | 'MD_MEng' | 'MD_MM' | 'RAK') | null;
    /**
     * Auto-syncs to the corresponding academic year group
     */
    year?: ('M_Eng_M_M' | 'Year_1' | 'Year_2' | 'Year_3' | 'Year_4' | 'Year_5' | 'Year_6') | null;
  };
  contact?: {
    line_id?: string | null;
    phone_number?: string | null;
  };
  social_media?:
    | {
        platform: string;
        handle: string;
        id?: string | null;
      }[]
    | null;
  portfolio?:
    | {
        year: '2023' | '2024' | '2025' | '2026' | '2027';
        activity: string;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  interests?:
    | (
        | 'special_lecture'
        | 'conference'
        | 'workshop_observe'
        | 'workshop_assistant'
        | 'workshop_full'
        | 'exchange'
        | 'volunteer'
        | 'event'
        | 'inspirational'
      )[]
    | null;
  notification_preferences?: {
    email_opt_in?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  name: string;
  /**
   * Unique identifier for code references (e.g. "admin", "od", "year-1")
   */
  slug: string;
  type: 'system' | 'role' | 'department' | 'year' | 'track' | 'access';
  description?: string | null;
  /**
   * Granular permissions configuration
   */
  permissions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Use this field to add or remove members from the group.
   */
  members?: (number | User)[] | null;
  /**
   * Read-only table of all users belonging to this group. Click a row to view the user.
   */
  members_table?: {
    docs?: (number | User)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  name: string;
  event_type:
    | 'special_lecture'
    | 'conference'
    | 'workshop_observe'
    | 'workshop_assistant'
    | 'workshop_full'
    | 'exchange'
    | 'volunteer'
    | 'event'
    | 'inspirational';
  department?: ('IA' | 'EA' | 'OD' | 'AD' | 'CC' | 'PR') | null;
  date_begin: string;
  date_end?: string | null;
  /**
   * Select a location from the predefined list
   */
  location?: (number | null) | Location;
  image_url?: string | null;
  description?: string | null;
  is_visible?: boolean | null;
  /**
   * Legacy info field (read-only)
   */
  info?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  subscription_form?: (number | null) | Form;
  registration_opens_at?: string | null;
  registration_closes_at?: string | null;
  /**
   * Maximum number of participants (0 = unlimited)
   */
  participant_limit?: number | null;
  is_registration_closed?: boolean | null;
  /**
   * Override automatic opening/closing times
   */
  status_override?: ('auto' | 'open' | 'closed') | null;
  /**
   * Automatically promote waiting list users when a slot opens
   */
  auto_promote?: boolean | null;
  /**
   * Limit size of waiting list (0 = unlimited)
   */
  max_waiting_list?: number | null;
  /**
   * Optional message included in the acceptance email
   */
  custom_acceptance_email?: string | null;
  /**
   * Add LINE group link, meeting location, instructions here. Only visible to users with "confirmed" status.
   */
  participant_detail?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Form users submit to request leave. Linked from the "Decline" button.
   */
  loa_form?: (number | null) | Form;
  reflection_form?: (number | null) | Form;
  is_reflection_open?: boolean | null;
  owner?: (number | null) | User;
  coordinator?: (number | null) | User;
  groups?: (number | Group)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  campus: string;
  building?: string | null;
  room?: string | null;
  /**
   * Auto-generated from campus, building, room
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'radio';
          }
        | {
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'date';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            variant?: ('rating' | 'stars' | 'slider') | null;
            min?: number | null;
            max?: number | null;
            step?: number | null;
            showLabels?: boolean | null;
            minLabel?: string | null;
            maxLabel?: string | null;
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'slider';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            options: {
              label: string;
              value: string;
              id?: string | null;
            }[];
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ranking';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            options: {
              label: string;
              value: string;
              id?: string | null;
            }[];
            minSelect?: number | null;
            maxSelect?: number | null;
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkboxGroup';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            accept?: string | null;
            maxSize?: number | null;
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'fileUpload';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            profileField:
              | 'email'
              | 'name_english.first_name'
              | 'name_english.last_name'
              | 'name_english.nickname'
              | 'name_thai.first_name'
              | 'name_thai.last_name'
              | 'name_thai.nickname'
              | 'academic.student_id'
              | 'academic.year'
              | 'academic.track'
              | 'contact.phone_number'
              | 'contact.line_id';
            readOnly?: boolean | null;
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'userProfile';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Toggle whether this form is currently accepting new responses.
   */
  accept_responses?: boolean | null;
  /**
   * Automatically close form after this date and time (optional).
   */
  response_deadline?: string | null;
  /**
   * Automatically close form after this many submissions (optional).
   */
  response_limit?: number | null;
  /**
   * Message to show when the form is closed (either manually or past deadline).
   */
  closed_message?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations".
 */
export interface Registration {
  id: number;
  event: number | Event;
  user: number | User;
  status?:
    | ('subscribed' | 'applicant' | 'accepted' | 'rejected' | 'confirmed' | 'declined' | 'participant' | 'withdrawn')
    | null;
  submission?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  selected_at?: string | null;
  selected_by?: (number | null) | User;
  rejection_reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-assignments".
 */
export interface FormAssignment {
  id: number;
  form: number | Form;
  user: number | User;
  assigned_by?: (number | null) | User;
  deadline?: string | null;
  completed?: boolean | null;
  /**
   * If checked, the user cannot register for events until this form is completed.
   */
  blocks_registration?: boolean | null;
  submission?: (number | null) | FormSubmission;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  user?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendings".
 */
export interface Attending {
  id: number;
  name_thai: {
    first_name: string;
    last_name: string;
  };
  name_english: {
    first_name: string;
    last_name: string;
  };
  title?: (number | null) | AcademicTitle;
  specialty?:
    | (
        | 'general_surgery'
        | 'cardiothoracic'
        | 'neurosurgery'
        | 'orthopedic'
        | 'plastic'
        | 'pediatric'
        | 'urology'
        | 'vascular'
        | 'oncology'
        | 'trauma'
        | 'transplant'
        | 'other'
      )
    | null;
  image_url?: string | null;
  contact?: {
    email?: string | null;
    phone_number?: string | null;
  };
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  is_visible?: boolean | null;
  /**
   * Lower numbers appear first
   */
  sort_order?: number | null;
  display_name?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academic_titles".
 */
export interface AcademicTitle {
  id: number;
  title_thai: string;
  title_english: string;
  /**
   * Auto-generated from Thai and English titles
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  /**
   * Link to user profile — pulls name, image, department from their account
   */
  user: number | User;
  position: string;
  academic_year: string;
  /**
   * Uncheck to move to Hall of Fame
   */
  is_current?: boolean | null;
  /**
   * Lower numbers appear first (President = 0, VP = 1, etc.)
   */
  sort_order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-requests".
 */
export interface FeatureRequest {
  id: number;
  type: 'bug' | 'feature';
  title: string;
  description: string;
  status?: ('open' | 'planned' | 'in_progress' | 'done' | 'closed') | null;
  admin_notes?: string | null;
  submitted_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null)
    | ({
        relationTo: 'registrations';
        value: number | Registration;
      } | null)
    | ({
        relationTo: 'form-assignments';
        value: number | FormAssignment;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'attendings';
        value: number | Attending;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'academic_titles';
        value: number | AcademicTitle;
      } | null)
    | ({
        relationTo: 'feature-requests';
        value: number | FeatureRequest;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  groups?: T;
  department?: T;
  google_id?: T;
  image_url?: T;
  dob?: T;
  age?: T;
  name_thai?:
    | T
    | {
        first_name?: T;
        last_name?: T;
        nickname?: T;
      };
  full_name_thai?: T;
  profile_complete?: T;
  name_english?:
    | T
    | {
        first_name?: T;
        last_name?: T;
        nickname?: T;
      };
  academic?:
    | T
    | {
        student_id?: T;
        track?: T;
        year?: T;
      };
  contact?:
    | T
    | {
        line_id?: T;
        phone_number?: T;
      };
  social_media?:
    | T
    | {
        platform?: T;
        handle?: T;
        id?: T;
      };
  portfolio?:
    | T
    | {
        year?: T;
        activity?: T;
        role?: T;
        id?: T;
      };
  interests?: T;
  notification_preferences?:
    | T
    | {
        email_opt_in?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  event_type?: T;
  department?: T;
  date_begin?: T;
  date_end?: T;
  location?: T;
  image_url?: T;
  description?: T;
  is_visible?: T;
  info?: T;
  subscription_form?: T;
  registration_opens_at?: T;
  registration_closes_at?: T;
  participant_limit?: T;
  is_registration_closed?: T;
  status_override?: T;
  auto_promote?: T;
  max_waiting_list?: T;
  custom_acceptance_email?: T;
  participant_detail?: T;
  loa_form?: T;
  reflection_form?: T;
  is_reflection_open?: T;
  owner?: T;
  coordinator?: T;
  groups?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  description?: T;
  permissions?: T;
  members?: T;
  members_table?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations_select".
 */
export interface RegistrationsSelect<T extends boolean = true> {
  event?: T;
  user?: T;
  status?: T;
  submission?: T;
  selected_at?: T;
  selected_by?: T;
  rejection_reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-assignments_select".
 */
export interface FormAssignmentsSelect<T extends boolean = true> {
  form?: T;
  user?: T;
  assigned_by?: T;
  deadline?: T;
  completed?: T;
  blocks_registration?: T;
  submission?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  campus?: T;
  building?: T;
  room?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendings_select".
 */
export interface AttendingsSelect<T extends boolean = true> {
  name_thai?:
    | T
    | {
        first_name?: T;
        last_name?: T;
      };
  name_english?:
    | T
    | {
        first_name?: T;
        last_name?: T;
      };
  title?: T;
  specialty?: T;
  image_url?: T;
  contact?:
    | T
    | {
        email?: T;
        phone_number?: T;
      };
  bio?: T;
  is_visible?: T;
  sort_order?: T;
  display_name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  user?: T;
  position?: T;
  academic_year?: T;
  is_current?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academic_titles_select".
 */
export interface AcademicTitlesSelect<T extends boolean = true> {
  title_thai?: T;
  title_english?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-requests_select".
 */
export interface FeatureRequestsSelect<T extends boolean = true> {
  type?: T;
  title?: T;
  description?: T;
  status?: T;
  admin_notes?: T;
  submitted_by?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        radio?:
          | T
          | {
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        date?:
          | T
          | {
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        slider?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              variant?: T;
              min?: T;
              max?: T;
              step?: T;
              showLabels?: T;
              minLabel?: T;
              maxLabel?: T;
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ranking?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        checkboxGroup?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              minSelect?: T;
              maxSelect?: T;
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        fileUpload?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              accept?: T;
              maxSize?: T;
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        userProfile?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              profileField?: T;
              readOnly?: T;
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  accept_responses?: T;
  response_deadline?: T;
  response_limit?: T;
  closed_message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content".
 */
export interface HomeContent {
  id: number;
  sections?:
    | {
        /**
         * Small label shown above the section title.
         */
        kicker?: string | null;
        heading: string;
        body: string;
        /**
         * Optional image URL for this section.
         */
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-content".
 */
export interface TermsContent {
  id: number;
  /**
   * Optional intro paragraph shown under the page heading.
   */
  intro?: string | null;
  sections?:
    | {
        title: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Controls whether language switching is enabled on the public site.
   */
  enableI18n?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content_select".
 */
export interface HomeContentSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
        imageUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-content_select".
 */
export interface TermsContentSelect<T extends boolean = true> {
  intro?: T;
  sections?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  enableI18n?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}